Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Settimana_3_Manuel.Models;
using Settimana_3_Manuel.Service;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Settimana_3_Manuel.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User user)
        {
            var u = _authService.Login(user.Name, user.Password);
            if (u == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, u.Name),
                new Claim(ClaimTypes.Email, u.Email),
                new Claim(ClaimTypes.NameIdentifier, u.Id.ToString())
            };
            u.Roles.ForEach(r => claims.Add(new Claim(ClaimTypes.Role, r.Name)));

            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(User user)
        {
            _authService.Register(user);
            return RedirectToAction("Login");
        }
    }
}

Controllers/IngredientController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Settimana_3_Manuel.Models;
using Settimana_3_Manuel.Service;

namespace Settimana_3_Manuel.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IngredientController : Controller
    {
        
        private readonly IIngredientService _ingredientService;

        public IngredientController(IIngredientService ingredientService)
        {
            _ingredientService = ingredientService;
        }
        // /////////////////////////////////////////////////////Get ALL/////////////////////////////////////////////////////
        public async Task<IActionResult> Index()
        {
            var ingredients = await _ingredientService.GetAll();
            return View(ingredients);
        }

        // ///////////////////////////////////////DETTAGLI///////////////////////////////////////////////////////////////////
        public async Task<IActionResult> Details(int id)
        {
            var ingredient = await _ingredientService.GetById(id);
            if (ingredient == null)
            {
                return NotFound();
            }
            return View(ingredient);
        }
        // ///////////////////////////////////////CREATE/////////////////////////////////////////////////////////////////

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Ingredient ingredient)
        {
            if (ModelState.IsValid)
            {
                await _ingredientService.Create(ingredient);
                return RedirectToAction(nameof(Index));
            }
            return View(ingredient);
        }

        // ///////////////////////////////////////EDIT///////////////////////////////////////////////////////////////////

        public async Task<IActionResult> Edit(int id)
        {
            var ingredient = await _ingredientService.GetById(id);
            if (ingredient == null)
            {
                return NotFound();
            }
            return View(ingredient);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Ingredient ingredient)
        {
            if (id != ingredient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _ingredientService.Update(ingredient);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await _ingredientService.GetById(ingredient.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ingredient);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var ingredient = await _ingredientService.GetById(id);
            if (ingredient == null)
            {
                return NotFound();
            }
            return View(ingredient);
        }

        // //////////////////////////////////////DELETE//////////////////////////////////////////////////////////////////

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _ingredientService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Settimana_3_Manuel.Service;
using System.Security.Claims;

namespace Settimana_3_Manuel.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;

        public OrderController(IOrderService orderService, IProductService productService)
        {
            _orderService = orderService;
            _productService = productService;
        }
        // ////////////////////////////////////INDEX///////////////////////////////////////////////

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var orders = await _orderService.GetUserOrders(userId);
            return View(orders);
        }

        // ////////////////////////////////////ADD TO ORDER///////////////////////////////////////////////
        
        [HttpPost]
        public async Task<IActionResult> AddToOrder(int productId, int quantity, string address, string extraNote)
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            await _orderService.AddToOrder(userId, productId, quantity, address, extraNote);
            return Ok(); 
        }

        // //////////////////////////////////ALL ORDERS/////////////////////////////////////////////////
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AllOrders()
        {
            var orders = await _orderService.GetAllOrders();
            return View(orders);
        }

        // //////////////////////////////////PROCESSED ORDERS/////////////////////////////////////////////////
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ProcessOrder(int orderId)
        {
            await _orderService.ProcessOrder(orderId);
            return RedirectToAction("AllOrders");
        }

        // ///////////////////////////////////////DELETE ORDERS//////////////////////////////////////////////////
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> DeleteOrder(int orderId)
        {
            await _orderService.DeleteOrder(orderId);
            return RedirectToAction("AllOrders");
        }




    }
}

Controllers/ProductController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Settimana_3_Manuel.Models;
using Settimana_3_Manuel.Service;

namespace Settimana_3_Manuel.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IIngredientService _ingredientService;

        public ProductController(IProductService productService, IIngredientService ingredientService)
        {
            _productService = productService;
            _ingredientService = ingredientService;
        }

        // ///////////////////////////////////////GET ALL///////////////////////////////////////////////////////////////////
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAll();
            return View(products);
        }


        // //////////////////////////////////////CREATE///////////////////////////////////////////////////////////////////
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var ingredients = await _ingredientService.GetAll();
            var viewModel = new ProductCreateViewModel
            {
                Ingredients = ingredients.ToList()
            };
            return View(viewModel);
        }

       
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var product = new Product
                {
                    Name = viewModel.Name,
                    Price = viewModel.Price,
                    DeliveryTimeInMinutes = viewModel.DeliveryTimeInMinutes,
                    Ingredients = new List<Ingredient>()
                };

                if (viewModel.Photo != null && viewModel.Photo.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        await viewModel.Photo.CopyToAsync(ms);
                        var fileBytes = ms.ToArray();
                        product.Photo = Convert.ToBase64String(fileBytes);
                    }
                }

                if (viewModel.SelectedIngredients != null)
                {
                    foreach (var ingredientId in viewModel.SelectedIngredients)
                    {
                        var ingredient = await _ingredientService.GetById(ingredientId);
                        if (ingredient != null)
                        {
                            product.Ingredients.Add(ingredient);
                        }
                    }
                }

                await _productService.Create(product);
                return RedirectToAction(nameof(Index));
            }

            viewModel.Ingredients = (await _ingredientService.GetAll()).ToList();
            return View(viewModel);
        }


        // ///////////////////////////////////////EDIT///////////////////////////////////////////////////////////////////

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productService.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            var ingredients = await _ingredientService.GetAll();
            var viewModel = new ProductCreateViewModel
            {
                Name = product.Name,
                Price = product.Price,
                DeliveryTimeInMinutes = product.DeliveryTimeInMinutes,
                Ingredients = ingredients.ToList(),
                SelectedIngredients = product.Ingredients.Select(i => i.Id).ToArray()
            };
            return View(viewModel);
        }

        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductCreateViewModel viewModel)
        {
            if (id != viewModel.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var product = await _productService.GetById(id);
                if (product == null)
                {
                    return NotFound();
                }

                product.Name = viewModel.Name;
                product.Price = viewModel.Price;
                product.DeliveryTimeInMinutes = viewModel.DeliveryTimeInMinutes;

                if (viewModel.Photo != null && viewModel.Photo.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        await viewModel.Photo.CopyToAsync(ms);
                        var fileBytes = ms.ToArray();
                        product.Photo = Convert.ToBase64String(fileBytes);
                    }
                }


                product.Ingredients.Clear();
                if (viewModel.SelectedIngredients != null)
                {
                    foreach (var ingredientId in viewModel.SelectedIngredients)
                    {
                        var ingredient = await _ingredientService.GetById(ingredientId);
                        if (ingredient != null)
                        {
                            product.Ingredients.Add(ingredient);
                        }
                    }
                }

                await _productService.Update(product);
                return RedirectToAction(nameof(Index));
            }

            viewModel.Ingredients = (await _ingredientService.GetAll()).ToList();
            return View(viewModel);
        }



        // ////////////////////////////////////////DELETE//////////////////////////////////////////////////////////

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productService.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);




        }

        // ///////////////////////////////////////GetProductIMAGE/////////////////////////////////////////////////////////////////

        [HttpGet]
        public async Task<IActionResult> GetProductImage(int id)
        {
            var product = await _productService.GetById(id);
            if (product == null || string.IsNullOrEmpty(product.Photo))
            {
                return NotFound();
            }

            byte[] imageBytes = Convert.FromBase64String(product.Photo);
            return File(imageBytes, "image/png");
        }


        // ///////////////////////////////////////DELETE///////////////////////////////////////////////////////////////////

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _productService.Delete(id);
        return RedirectToAction(nameof(Index));
    }




}



    }











    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Settimana_3_Manuel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Settimana_3_Manuel.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header class="fixed-top ">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="/images/Pizza.jpg" alt="Logo" style="height: 60px; margin-right: 25px;" />
               
            </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="AllOrders">All Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ingredient" asp-action="Index">Ingredients</a>
                            </li>
                        }

                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity?.IsAuthenticated ?? false)
                    {
                        <span class="navbar-text ms-auto">Welcome back, @User.Identity.Name!</span>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5 pt-5 pb-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-5 fixed-bottom">
        <div class="container py-3 text-white">
            <div class="row">
                <div class="col-md-6 text-center text-md-left">
                    &copy; 2024 - In Forno - <a class="text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
                <div class="col-md-6 text-center text-md-right">
                    <a href="#" class="text-white mx-2"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="text-white mx-2"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="text-white mx-2"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </footer >
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>